doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '12.5'
        charset: 'utf8'
        schema_filter: '~^(?!domain_)~'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ReadModel:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Projection'
                prefix: 'App\Projection'
                alias: ReadModel
