security:
    providers:
        database:
            id: App\Infrastructure\User\Security\AuthUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            guard:
                authenticators:
                    - App\Infrastructure\User\Security\GoogleAuthenticator
            logout:
                path: security.logout
