version: '3'

services:
  app:
    image: brpauwels/php:8.0-xdebug
    volumes:
      - ../..:/opt/app:cached
    environment:
      - VIRTUAL_HOST=weekly-meal.docker
      - VIRTUAL_PORT=8080
      - CORS_ENABLED=true
    env_file:
      - ../../.env
    ports:
      - 8080
    depends_on:
      - postgres

  postgres:
    image: library/postgres:12.5-alpine
    environment:
      - POSTGRES_USER=weekly-meal
      - POSTGRES_DB=weekly-meal
      - POSTGRES_PASSWORD=weekly-meal

networks:
  default:
    external:
      name: integration_default
